/* Sukoon — shared renderer for the "AI Care Agent Network" view.
   Used by the caregiver, doctor and family dashboards. Pure rendering only —
   each dashboard's own controller fetches its role-scoped
   /api/{role}/patients/{id}/agentic payload and passes it in here, then
   calls wireAgentNetworkExtras() to hook up the "Ask Sukoon" box and the
   multi-patient triage panel (both need their own API calls). */

function renderAgentNetworkHTML(data) {
  const risk = data.risk;
  const statusLabel = { active: "Active", watching: "Watching", attention: "Needs attention", idle: "Idle" };
  const agentCards = data.agents.map((a) => `
    <div class="sk-agent-card status-${a.status}">
      <div class="sk-agent-card-head"><span class="sk-agent-icon">${a.icon}</span><span class="sk-agent-name">${skEscape(a.name)}</span></div>
      <div class="sk-agent-watches">Watches: ${skEscape(a.watches)}</div>
      <div class="sk-agent-summary">${skEscape(a.summary)}</div>
      <span class="sk-agent-status-pill status-${a.status}">${statusLabel[a.status] || a.status}</span>
    </div>
  `).join("");

  const escRows = data.escalations.length
    ? data.escalations.map((e) => `
      <div class="sk-esc-row">
        <span class="sk-esc-icon">${e.icon}</span>
        <div><div>${skEscape(e.reason)}</div><div class="sk-esc-meta">${skEscape(e.agent)} → ${skEscape(e.action)} · ${skTimeAgo(e.at)}</div></div>
      </div>`).join("")
    : '<div class="sk-empty">No escalations — everything has stayed within normal bounds.</div>';

  const tlRows = data.timeline.length
    ? data.timeline.slice(0, 12).map((t) => `
      <div class="sk-tl-row">
        <span class="sk-tl-icon">${t.icon}</span>
        <div><div>${skEscape(t.label)}</div><div class="sk-tl-meta">${skEscape(t.source)} · ${skTimeAgo(t.at)}</div></div>
      </div>`).join("")
    : '<div class="sk-empty">No activity logged yet.</div>';

  const anomaly = data.cognitive_anomaly;
  const anomalyHTML = anomaly && anomaly.flagged ? `
    <div class="sk-disclaimer" style="background:#fdf1de; border-color:#f0d9ad; margin-bottom:16px;">
      ⚠️ <strong>Cognitive trend anomaly detected:</strong> ${skEscape(anomaly.message)}
    </div>` : "";

  const fam = data.family_engagement || [];
  const famHTML = fam.length ? fam.map((f) => `
    <div class="sk-esc-row">
      <span class="sk-esc-icon">${f.status === "attention" ? "⚠️" : f.status === "watching" ? "🕒" : "✅"}</span>
      <div><div>${skEscape(f.name)} <span style="color:var(--sukoon-ink-500); font-weight:400;">(${skEscape(f.relationship)})</span></div><div class="sk-esc-meta">${skEscape(f.note)}</div></div>
    </div>`).join("") : '<div class="sk-empty">No family members linked yet.</div>';

  const timing = data.adaptive_timing || [];
  const timingHTML = timing.length ? timing.map((t) => `
    <div class="sk-tl-row">
      <span class="sk-tl-icon">⏱️</span>
      <div><div>${skEscape(t.suggestion)}</div></div>
    </div>`).join("") : '<div class="sk-empty">No timing adjustments suggested right now — response times look consistent.</div>';

  const medSafety = data.medication_safety || { flags: [] };
  const medHTML = medSafety.flags && medSafety.flags.length ? medSafety.flags.map((f) => `
    <div class="sk-esc-row">
      <span class="sk-esc-icon">⚠️</span>
      <div><div>${skEscape(f.drugs.join(" + "))}</div><div class="sk-esc-meta">${skEscape(f.note)}</div></div>
    </div>`).join("") : '<div class="sk-empty">No known interaction flags found among logged medicines.</div>';

  const brief = data.clinical_brief || {};
  const llmBadge = data.llm_enabled
    ? '<span class="sk-badge sk-badge-info">Generated by LLM</span>'
    : '<span class="sk-badge sk-badge-neutral">Rule-based (LLM upgrade available)</span>';

  return `
    <div class="sk-disclaimer" style="margin-bottom:16px;">Sukoon's care agents are transparent, rule-based monitors over this patient's own logged data — five specialised agents plus a coordinating escalation agent, every decision traceable to a real signal. Not a black-box model, not a medical device.</div>

    <div class="sk-card" style="margin-bottom:16px; display:flex; gap:12px; align-items:flex-start;">
      <div style="font-size:1.5rem;">📋</div>
      <div><strong>Today's Briefing:</strong> ${skEscape(data.daily_briefing.text)}</div>
    </div>

    ${anomalyHTML}

    <div class="sk-card sk-risk-card" style="margin-bottom:18px;">
      <div class="sk-risk-dial ${risk.band}"><span class="num">${risk.score}</span><span class="lbl">${risk.label}</span></div>
      <div>
        <h3 style="margin:0 0 6px;">Wellness Risk Score</h3>
        <ul class="sk-risk-factors">${risk.factors.map((f) => `<li>${skEscape(f)}</li>`).join("")}</ul>
      </div>
    </div>

    <h3 style="margin:18px 0 4px;">Agent Network</h3>
    <div class="sk-agent-grid">${agentCards}</div>

    <div class="sk-card" style="margin-top:22px;">
      <h3 style="margin-top:0;">💬 Ask Sukoon</h3>
      <div style="font-size:0.82rem; color:var(--sukoon-ink-500); margin-bottom:10px;">Ask about medicine, water, meals, mood, appointments, location, journal recall, or overall risk — answered live from this patient's real data.</div>
      <form id="askSukoonForm" style="display:flex; gap:8px;">
        <input type="text" id="askSukoonInput" placeholder="e.g. did she take her medicine today?" style="flex:1; padding:10px 12px; border-radius:10px; border:1px solid var(--sukoon-line); font-size:0.9rem;">
        <button class="sk-btn sk-btn-primary" type="submit">Ask</button>
      </form>
      <div id="askSukoonAnswer" style="margin-top:12px;"></div>
    </div>

    <div id="triagePanel"></div>

    <div class="sk-grid sk-grid-2" style="margin-top:22px;">
      <div class="sk-card">
        <h3 style="margin-top:0;">Escalation Log</h3>
        ${escRows}
      </div>
      <div class="sk-card">
        <h3 style="margin-top:0;">Unified Care Timeline</h3>
        ${tlRows}
      </div>
    </div>

    <div class="sk-grid sk-grid-2" style="margin-top:22px;">
      <div class="sk-card">
        <h3 style="margin-top:0;">🩺 Clinical Insight ${llmBadge}</h3>
        <div style="font-size:0.88rem; line-height:1.6;">${skEscape(brief.text || "Not enough data yet.")}</div>
      </div>
      <div class="sk-card">
        <h3 style="margin-top:0;">👨‍👩‍👧 Family Engagement</h3>
        ${famHTML}
      </div>
    </div>

    <div class="sk-grid sk-grid-2" style="margin-top:22px;">
      <div class="sk-card">
        <h3 style="margin-top:0;">⏱️ Adaptive Reminder Timing</h3>
        ${timingHTML}
      </div>
      <div class="sk-card">
        <h3 style="margin-top:0;">💊 Medication Safety Check</h3>
        ${medHTML}
        <div style="font-size:0.72rem; color:var(--sukoon-ink-500); margin-top:10px;">${skEscape(medSafety.disclaimer || "")}</div>
      </div>
    </div>
  `;
}

function renderTriagePanelHTML(rows) {
  if (!rows || rows.length < 2) return "";
  const bandColor = { high: "#e0455b", medium: "var(--sukoon-amber-600)", low: "var(--sukoon-teal-700)" };
  return `
    <div class="sk-card" style="margin-top:22px;">
      <h3 style="margin-top:0;">🚦 Priority Queue — all your patients, risk-ranked</h3>
      ${rows.map((r, i) => `
        <div class="sk-tl-row">
          <span class="sk-tl-icon">${i === 0 ? "🔴" : i === 1 ? "🟠" : "🟢"}</span>
          <div style="flex:1;">
            <div><strong>${skEscape(r.name)}</strong> — <span style="color:${bandColor[r.risk_band] || 'inherit'}; font-weight:700;">${r.risk_score}/100 (${skEscape(r.risk_label)})</span></div>
            <div class="sk-tl-meta">${r.recent_escalations} recent escalation(s)</div>
          </div>
        </div>
      `).join("")}
    </div>
  `;
}

/* Wires the "Ask Sukoon" form and (if there's more than one patient) the
   triage panel. apiPrefix e.g. "/api/caregiver". patients: array with .id. */
function wireAgentNetworkExtras(apiPrefix, patientId, patients) {
  const form = document.getElementById("askSukoonForm");
  if (form) {
    form.addEventListener("submit", async (e) => {
      e.preventDefault();
      const input = document.getElementById("askSukoonInput");
      const answerBox = document.getElementById("askSukoonAnswer");
      const text = input.value.trim();
      if (!text) return;
      answerBox.innerHTML = `<div class="sk-loading">Thinking…</div>`;
      try {
        const res = await SukoonAPI.post(`${apiPrefix}/patients/${patientId}/ask`, { text });
        answerBox.innerHTML = `<div class="sk-esc-row"><span class="sk-esc-icon">🤖</span><div>${skEscape(res.answer)}</div></div>`;
      } catch (err) {
        answerBox.innerHTML = `<div class="sk-empty">${skEscape(err.message)}</div>`;
      }
    });
  }

  const triageDiv = document.getElementById("triagePanel");
  if (triageDiv && patients && patients.length > 1) {
    SukoonAPI.get(`${apiPrefix}/triage`).then((rows) => {
      triageDiv.innerHTML = renderTriagePanelHTML(rows);
    }).catch(() => {});
  }
}
